apiVersion: v1
kind: Service
metadata:
  name: vehicle-parking-service
spec:
  type: NodePort
  selector:
    app: vehicle-parking
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007
